Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2019-07, with the labels that each got.

#265 [RHDM-1002] Remove decisioncentral-indexing image and reference in streams
  README.md
  ce.yaml
  decisioncentral-indexing/branch-overrides.yaml
  decisioncentral-indexing/container.yaml
  decisioncentral-indexing/content_sets.yml
  decisioncentral-indexing/image.yaml
  decisioncentral-indexing/tag-overrides.yaml
  decisioncentral/image.yaml
  rhdm74-image-streams.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#267 [RHDM-1002] Remove decisioncentral-indexing image and reference in streams
  README.md
  ce.yaml
  decisioncentral-indexing/branch-overrides.yaml
  decisioncentral-indexing/container.yaml
  decisioncentral-indexing/content_sets.yml
  decisioncentral-indexing/image.yaml
  decisioncentral-indexing/tag-overrides.yaml
  decisioncentral/image.yaml
  rhdm75-image-streams.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#264 [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#266 [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
  templates/rhdm75-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#270 [KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …
  templates/docs/rhdm74-optaweb-employee-rostering.adoc
  templates/docs/rhdm74-prod-immutable-kieserver-amq.adoc
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#271 [KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …
  templates/docs/rhdm74-authoring-ha.adoc
  templates/docs/rhdm74-authoring.adoc
  templates/docs/rhdm74-kieserver.adoc
  templates/docs/rhdm74-optaweb-employee-rostering.adoc
  templates/docs/rhdm74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm74-prod-immutable-kieserver.adoc
  templates/docs/rhdm74-trial-ephemeral.adoc
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#273 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  controller/image.yaml
  controller/tag-overrides.yaml
  decisioncentral/image.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  optaweb-employee-rostering/image.yaml
  optaweb-employee-rostering/tag-overrides.yaml
  quickstarts/hello-rules-multi-module/README.md
  quickstarts/hello-rules/README.md
  rhdm74-image-streams.yaml
  templates/docs/README.adoc
  templates/docs/rhdm74-authoring-ha.adoc
  templates/docs/rhdm74-authoring.adoc
  templates/docs/rhdm74-kieserver.adoc
  templates/docs/rhdm74-optaweb-employee-rostering.adoc
  templates/docs/rhdm74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm74-prod-immutable-kieserver.adoc
  templates/docs/rhdm74-trial-ephemeral.adoc
  templates/rhdm74-authoring-ha.yaml
  templates/rhdm74-authoring.yaml
  templates/rhdm74-kieserver.yaml
  templates/rhdm74-optaweb-employee-rostering.yaml
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
  templates/rhdm74-prod-immutable-kieserver.yaml
  templates/rhdm74-trial-ephemeral.yaml
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#274 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  templates/docs/README.adoc
  templates/docs/rhdm74-kieserver.adoc
  templates/docs/rhdm74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm74-prod-immutable-kieserver.adoc
  templates/docs/rhdm74-trial-ephemeral.adoc
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#275 [KIECLOUD-291] bring adoc generation fixes from 7.4.1 to 7.5.0
  templates/docs/README.adoc
  templates/docs/rhdm75-authoring-ha.adoc
  templates/docs/rhdm75-authoring.adoc
  templates/docs/rhdm75-kieserver.adoc
  templates/docs/rhdm75-optaweb-employee-rostering.adoc
  templates/docs/rhdm75-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm75-prod-immutable-kieserver.adoc
  templates/docs/rhdm75-trial-ephemeral.adoc
Labels: master ⇨ 7.5.0, ready 🚀
