Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2019-09, with the labels that each got.

#285 [RHDM-1057] - Review and update Authoring HA template for latest changes
  templates/rhdm75-authoring-ha.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#283 [KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3
  controller/branch-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/image.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  optaweb-employee-rostering/branch-overrides.yaml
  optaweb-employee-rostering/image.yaml
  optaweb-employee-rostering/tag-overrides.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#284 [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
  templates/rhdm75-authoring-ha.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#286 Update AMQ image version for kieserver jms integration
  templates/rhdm75-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#288 [BXMSDOC-4566] Misha's edits September 2019 7.5.x
  templates/rhdm75-authoring-ha.yaml
  templates/rhdm75-authoring.yaml
  templates/rhdm75-kieserver.yaml
  templates/rhdm75-optaweb-employee-rostering.yaml
  templates/rhdm75-prod-immutable-kieserver-amq.yaml
  templates/rhdm75-prod-immutable-kieserver.yaml
  templates/rhdm75-trial-ephemeral.yaml
Labels: 7.5.x ⇨ 7.5.0, ready 🚀

#287 [BXMSDOC-4566] Misha's edits September 2019
  templates/rhdm76-authoring-ha.yaml
  templates/rhdm76-authoring.yaml
  templates/rhdm76-kieserver.yaml
  templates/rhdm76-optaweb-employee-rostering.yaml
  templates/rhdm76-prod-immutable-kieserver-amq.yaml
  templates/rhdm76-prod-immutable-kieserver.yaml
  templates/rhdm76-trial-ephemeral.yaml
Labels: master ⇨ 7.6.0, ready 🚀

#289 regen adocs for 7.5.0
  templates/docs/rhdm75-authoring-ha.adoc
  templates/docs/rhdm75-authoring.adoc
  templates/docs/rhdm75-kieserver.adoc
  templates/docs/rhdm75-optaweb-employee-rostering.adoc
  templates/docs/rhdm75-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm75-prod-immutable-kieserver.adoc
  templates/docs/rhdm75-trial-ephemeral.adoc
Labels: 7.5.x ⇨ 7.5.0, ready 🚀

#290 regen adocs for 7.6.0
  templates/docs/rhdm76-authoring-ha.adoc
  templates/docs/rhdm76-authoring.adoc
  templates/docs/rhdm76-kieserver.adoc
  templates/docs/rhdm76-optaweb-employee-rostering.adoc
  templates/docs/rhdm76-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm76-prod-immutable-kieserver.adoc
  templates/docs/rhdm76-trial-ephemeral.adoc
Labels: master ⇨ 7.6.0, ready 🚀

#294 [ADOCS_REGEN] regenerate adocs per recent changes
  templates/docs/rhdm75-trial-ephemeral.adoc
Labels: 7.5.x ⇨ 7.5.0, ready 🚀
