Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2019-06, with the labels that each got.

#253 [KIECLOUD-232] - Update images of "amq-broker" to version 7.3
  templates/docs/rhdm74-authoring-ha.adoc
  templates/rhdm74-authoring-ha.yaml
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#255 [KIECLOUD-97] Synchronize OpenShiftStartupStrategy related changes between Template, APB, and Operator
  templates/rhdm74-authoring-ha.yaml
  templates/rhdm74-authoring.yaml
  templates/rhdm74-kieserver.yaml
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
  templates/rhdm74-prod-immutable-kieserver.yaml
  templates/rhdm74-trial-ephemeral.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#259 [RHDM-894] fix osbs repo branch suffix per clarified release guidelines
  controller/image.yaml
  decisioncentral-indexing/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
  optaweb-employee-rostering/image.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#260 [RHDM-894] fix osbs repo branch suffix per clarified release guidelines
  controller/image.yaml
  decisioncentral-indexing/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
  optaweb-employee-rostering/image.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#263 [RHDM-997] - Setting XA Datasource Postgres variable names (7.5.x)
  templates/rhdm75-optaweb-employee-rostering.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#262 [RHDM-997] - Setting XA Datasource Postgres variable names
  templates/rhdm74-optaweb-employee-rostering.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀
