Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2019-03, with the labels that each got.

#220 [KIECLOUD-158] - Generate templates' docs for RHPAM and RHDM 7.3.x br…
  templates/docs/README.adoc
  templates/docs/rhdm73-authoring-ha.adoc
  templates/docs/rhdm73-authoring.adoc
  templates/docs/rhdm73-kieserver.adoc
  templates/docs/rhdm73-optaweb-employee-rostering-mysql.adoc
  templates/docs/rhdm73-optaweb-employee-rostering-postgresql.adoc
  templates/docs/rhdm73-optaweb-employee-rostering-trial-ephemeral.adoc
  templates/docs/rhdm73-optaweb-employee-rostering.adoc
  templates/docs/rhdm73-prod-immutable-kieserver.adoc
  templates/docs/rhdm73-trial-ephemeral.adoc
Labels: 7.3.x ⇨ 7.3.0, ready 🚀

#221 [KIECLOUD-119] - Add Readme files to the Product image repositories.
  README.md
Labels: master ⇨ 7.4.0, ready 🚀

#207 [KIECLOUD-122] - Enable JMS for RHDM and RHPAM images.
  kieserver/image.yaml
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#196 [RHDM-848] - User password is been exposed in the Readiness probe and…
  templates/rhdm74-authoring-ha-datagrid.yaml
  templates/rhdm74-authoring-ha.yaml
  templates/rhdm74-authoring.yaml
  templates/rhdm74-kieserver.yaml
  templates/rhdm74-optaweb-employee-rostering.yaml
  templates/rhdm74-prod-immutable-kieserver-amq.yaml
  templates/rhdm74-prod-immutable-kieserver.yaml
  templates/rhdm74-trial-ephemeral.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#224 [RHDM-883] Setting Maven Mirror URL does not exclude Decision Central
  templates/rhdm74-authoring-ha-datagrid.yaml
  templates/rhdm74-authoring-ha.yaml
  templates/rhdm74-authoring.yaml
  templates/rhdm74-kieserver.yaml
  templates/rhdm74-prod-immutable-kieserver.yaml
  templates/rhdm74-trial-ephemeral.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#223 [RHDM-883] Setting Maven Mirror URL does not exclude Decision Central
  templates/rhdm73-authoring-ha.yaml
  templates/rhdm73-authoring.yaml
  templates/rhdm73-kieserver.yaml
  templates/rhdm73-prod-immutable-kieserver.yaml
  templates/rhdm73-trial-ephemeral.yaml
Labels: 7.3.x ⇨ 7.3.1, ready 🚀
