Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2020-10, with the labels that each got.

#370 [KIECLOUD] - Prepare RHPAM and RHDM repositories for 7.9.0 release
  controller/branch-overrides.yaml
  decisioncentral/branch-overrides.yaml
  kieserver/branch-overrides.yaml
  templates/docs/README.adoc
  templates/docs/rhdm79-authoring-ha.adoc
  templates/docs/rhdm79-authoring.adoc
  templates/docs/rhdm79-kieserver.adoc
  templates/docs/rhdm79-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm79-prod-immutable-kieserver.adoc
  templates/docs/rhdm79-trial-ephemeral.adoc
Labels: 7.9.x ⇨ 7.9.0, needs review :mag:

#371 [KIECLOUD-451] - Update txn-recovery-marker and update EAP 7.3.2 tag …
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: needs review :mag:

#372 [KIECLOUD-446] - Prepare RHPAM and RHDM master branch for next release
  .circleci/config.yml
  README.md
  controller/README.adoc
  controller/image.yaml
  controller/tag-overrides.yaml
  decisioncentral/README.adoc
  decisioncentral/image.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/README.adoc
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  quickstarts/hello-rules-multi-module/README.md
  quickstarts/hello-rules/README.md
  rhdm710-image-streams.yaml
  templates/docs/README.adoc
  templates/docs/rhdm710-authoring-ha.adoc
  templates/docs/rhdm710-authoring.adoc
  templates/docs/rhdm710-kieserver.adoc
  templates/docs/rhdm710-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm710-prod-immutable-kieserver.adoc
  templates/docs/rhdm710-trial-ephemeral.adoc
  templates/rhdm710-authoring-ha.yaml
  templates/rhdm710-authoring.yaml
  templates/rhdm710-kieserver.yaml
  templates/rhdm710-prod-immutable-kieserver-amq.yaml
  templates/rhdm710-prod-immutable-kieserver.yaml
  templates/rhdm710-trial-ephemeral.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#373 [BXMSDOC-6663] Editorial change - add comma
  templates/rhdm79-authoring-ha.yaml
  templates/rhdm79-authoring.yaml
  templates/rhdm79-kieserver.yaml
  templates/rhdm79-prod-immutable-kieserver-amq.yaml
  templates/rhdm79-prod-immutable-kieserver.yaml
  templates/rhdm79-trial-ephemeral.yaml
Labels: needs review :mag:

#374 [BXMSDOC-6663] Editorial change - add comma
  templates/rhdm710-authoring-ha.yaml
  templates/rhdm710-authoring.yaml
  templates/rhdm710-kieserver.yaml
  templates/rhdm710-prod-immutable-kieserver-amq.yaml
  templates/rhdm710-prod-immutable-kieserver.yaml
  templates/rhdm710-trial-ephemeral.yaml
Labels: needs review :mag:
