Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2020-11, with the labels that each got.

#377 Add Kaitou to default reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#375 [RHPAM-3245] - Change resource requirements for BC and KIE Server
  templates/rhdm710-authoring-ha.yaml
  templates/rhdm710-authoring.yaml
  templates/rhdm710-kieserver.yaml
  templates/rhdm710-prod-immutable-kieserver-amq.yaml
  templates/rhdm710-prod-immutable-kieserver.yaml
  templates/rhdm710-trial-ephemeral.yaml
Labels: needs review :mag:

#376 [RHPAM-3245-Cherrypick] - Change resource requirements for BC and KIE…
  templates/rhdm79-authoring-ha.yaml
  templates/rhdm79-authoring.yaml
  templates/rhdm79-kieserver.yaml
  templates/rhdm79-prod-immutable-kieserver-amq.yaml
  templates/rhdm79-prod-immutable-kieserver.yaml
  templates/rhdm79-trial-ephemeral.yaml
Labels: needs review :mag:

#379 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  templates/rhdm79-authoring-ha.yaml
  templates/rhdm79-authoring.yaml
  templates/rhdm79-trial-ephemeral.yaml
Labels: 7.9.x ⇨ 7.9.0, needs review :mag:

#378 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  templates/rhdm710-authoring-ha.yaml
  templates/rhdm710-authoring.yaml
  templates/rhdm710-trial-ephemeral.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#382 [RHDM-1432] Update EAP version from 7.3.3 on PAM/DM
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  decisioncentral/artifact-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#381 [RHDM-1432] Update EAP version from 7.3.3 on PAM/DM 7.9.x
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  decisioncentral/artifact-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#383 [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#384 [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#386 [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release
  controller/README.adoc
  controller/image.yaml
  controller/tag-overrides.yaml
  decisioncentral/README.adoc
  decisioncentral/image.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/README.adoc
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  rhdm79-image-streams.yaml
  templates/docs/rhdm79-authoring-ha.adoc
  templates/docs/rhdm79-authoring.adoc
  templates/docs/rhdm79-kieserver.adoc
  templates/docs/rhdm79-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm79-prod-immutable-kieserver.adoc
  templates/docs/rhdm79-trial-ephemeral.adoc
  templates/rhdm79-authoring-ha.yaml
  templates/rhdm79-authoring.yaml
  templates/rhdm79-kieserver.yaml
  templates/rhdm79-prod-immutable-kieserver-amq.yaml
  templates/rhdm79-prod-immutable-kieserver.yaml
  templates/rhdm79-trial-ephemeral.yaml
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:

#385 [KIECLOUD-466] - Avail the possibility to use the ubi8-mininal as bas…
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: needs review :mag:
