Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2021-11, with the labels that each got.

#446 [KIECLOUD-544] - Combine the prometheus agent and config modules
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#449 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  templates/rhdm712-authoring-ha.yaml
Labels: 7.12.x ⇨ 7.12.0

#450 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  templates/rhdm713-authoring-ha.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#445 [KIECLOUD-594] Migrate the access_log_valve script to wildfly-cekit-modules
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#454 [KIECLOUD-578]Upgrade wildfly-cekit-modules to include Keycloak support for SSO 7.5
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0

#455 [KIECLOUD-578] Upgrade wildfly-cekit-modules to include Keycloak support for SSO 7.5
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  decisioncentral/branch-overrides.yaml
  decisioncentral/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#448 [KIECLOUD-505] Update https.sh script to use the one provided by wildfly-cekit-modules
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, main ⇨ 7.13.0
