Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2021-12, with the labels that each got.

#459 [RHPAM-4064] BC HA does not start because of outdated configuration
  decisioncentral/image.yaml
  templates/rhdm713-authoring-ha.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#457 [RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admi…
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
  templates/rhdm713-authoring-ha.yaml
  templates/rhdm713-authoring.yaml
  templates/rhdm713-kieserver.yaml
  templates/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/rhdm713-prod-immutable-kieserver.yaml
  templates/rhdm713-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:, needs-cherry-pick :cherries:

#460 [RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admin perspective
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
  templates/rhdm712-authoring-ha.yaml
  templates/rhdm712-authoring.yaml
  templates/rhdm712-kieserver.yaml
  templates/rhdm712-prod-immutable-kieserver-amq.yaml
  templates/rhdm712-prod-immutable-kieserver.yaml
  templates/rhdm712-trial-ephemeral.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0, cherry-pick :cherries:

#463 docs review - capitalize all ldap occurrencies
  templates/rhdm713-authoring-ha.yaml
  templates/rhdm713-authoring.yaml
  templates/rhdm713-kieserver.yaml
  templates/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/rhdm713-prod-immutable-kieserver.yaml
  templates/rhdm713-trial-ephemeral.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#462 docs review - capitalize all ldap occurrencies
  templates/rhdm712-authoring-ha.yaml
  templates/rhdm712-authoring.yaml
  templates/rhdm712-kieserver.yaml
  templates/rhdm712-prod-immutable-kieserver-amq.yaml
  templates/rhdm712-prod-immutable-kieserver.yaml
  templates/rhdm712-trial-ephemeral.yaml
Labels: needs review :mag:

#461 update templates's adoc
  templates/docs/rhdm712-authoring-ha.adoc
  templates/docs/rhdm712-authoring.adoc
  templates/docs/rhdm712-kieserver.adoc
  templates/docs/rhdm712-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm712-prod-immutable-kieserver.adoc
  templates/docs/rhdm712-trial-ephemeral.adoc
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#464 update templates's adoc
  templates/docs/rhdm713-authoring-ha.adoc
  templates/docs/rhdm713-authoring.adoc
  templates/docs/rhdm713-kieserver.adoc
  templates/docs/rhdm713-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm713-prod-immutable-kieserver.adoc
  templates/docs/rhdm713-trial-ephemeral.adoc
Labels: needs review :mag:, main ⇨ 7.13.0

#466 fix small typo on ldap keep non mapped roles
  templates/rhdm713-authoring-ha.yaml
  templates/rhdm713-authoring.yaml
  templates/rhdm713-kieserver.yaml
  templates/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/rhdm713-prod-immutable-kieserver.yaml
  templates/rhdm713-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#465 fix small typo on ldap keep non mapped roles
  templates/rhdm712-authoring-ha.yaml
  templates/rhdm712-authoring.yaml
  templates/rhdm712-kieserver.yaml
  templates/rhdm712-prod-immutable-kieserver-amq.yaml
  templates/rhdm712-prod-immutable-kieserver.yaml
  templates/rhdm712-trial-ephemeral.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0, needs-cherry-pick :cherries:

#467 [KIECLOUD-614] - Application Templates still referencing the AUTH_LDA…
  templates/rhdm712-authoring-ha.yaml
  templates/rhdm712-authoring.yaml
  templates/rhdm712-kieserver.yaml
  templates/rhdm712-prod-immutable-kieserver-amq.yaml
  templates/rhdm712-prod-immutable-kieserver.yaml
  templates/rhdm712-trial-ephemeral.yaml
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:, needs-cherry-pick :cherries:

#469 update adocs due KIECLOUD-614
  templates/docs/rhdm712-authoring-ha.adoc
  templates/docs/rhdm712-authoring.adoc
  templates/docs/rhdm712-kieserver.adoc
  templates/docs/rhdm712-prod-immutable-kieserver-amq.adoc
  templates/docs/rhdm712-prod-immutable-kieserver.adoc
  templates/docs/rhdm712-trial-ephemeral.adoc
Labels: needs review :mag:

#468 [KIECLOUD-614] - Application Templates still referencing the AUTH_LDA…
  templates/rhdm713-authoring-ha.yaml
  templates/rhdm713-authoring.yaml
  templates/rhdm713-kieserver.yaml
  templates/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/rhdm713-prod-immutable-kieserver.yaml
  templates/rhdm713-trial-ephemeral.yaml
Labels: needs review :mag:, main ⇨ 7.13.0, cherry-pick :cherries:
