Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2021-02, with the labels that each got.

#404 [RHPAM-3246] - OCP Kie Server image with enable JMS integration missi…
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: 7.10.x ⇨ 7.10.0, ready 🚀

#405 [RHPAM-3246] - OCP Kie Server image with enable JMS integration missi…
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#407 [KIECLOUD-490] - Provide Make command to build rhdm images
  Makefile
  README.md
Labels: master ⇨ 7.11.0, ready 🚀

#402 [RHDM-1580] - Set image resources in templates to same values as in …
  templates/rhdm711-authoring-ha.yaml
  templates/rhdm711-authoring.yaml
  templates/rhdm711-kieserver.yaml
  templates/rhdm711-prod-immutable-kieserver-amq.yaml
  templates/rhdm711-prod-immutable-kieserver.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#399 [RHDM-1580] - Set image resources in templates to same values as in...
  templates/rhdm710-authoring-ha.yaml
  templates/rhdm710-authoring.yaml
  templates/rhdm710-kieserver.yaml
  templates/rhdm710-prod-immutable-kieserver-amq.yaml
  templates/rhdm710-prod-immutable-kieserver.yaml
Labels: 7.10.x ⇨ 7.10.1, ready 🚀
