Repository jboss-container-images/rhdm-7-openshift-image, pull requests merged in 2022-01, with the labels that each got.

#470 [RHPAM-4109] Cannot open created project - FileSystem Index fails - Nullpointer
  templates/rhdm712-authoring-ha.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0

#471 RHPAM-4109 Cannot open created project - FileSystem Index fails - NullPointerException
  templates/rhdm713-authoring-ha.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#472 update templates' adoc
  templates/docs/rhdm712-authoring-ha.adoc
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#473 Updated Reviewers file to include davidesalerno
  .github/bot-files/reviewers.yml
Labels: ready 🚀

#451 [KIECLOUD-594] 7.12.x Migrate the access_log_valve script to wildfly-cekit-modules
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#447 [KIECLOUD-544] - Combine the prometheus agent and config modules
  controller/image.yaml
  decisioncentral/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.1
